# Setup
title:               'Soori Home'
tagline:             '안녕_'
description:         '매일 아침 일어나 다시 잠에 드는 삶...'
url:                 'https://soorichu.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Soori
  url:               ''
  email:             soorichu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# 테마 구조
navigation:
  - title: "Home"
    url: "/"
  - title: "EinkNote"
    url: "/einknote/"

# Custom vars
version:             2.1.0
google_analytics_id: 'G-ND8E2PZLQW'
