# Setup
title:               'Soori Home'
tagline:             ''
description:         'My first Eink Note'
baseurl:                 ''
url:             'https://www.einknote.cloud'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Soori
  url:               ''
  email:             soorichu@gmail.com

# Gems
plugins:
  - jekyll-paginate


# Custom vars
version:             2.1.0
google_analytics_id: 'G-ND8E2PZLQW'
